## 📄 pubspec.yaml (minimal)
```yaml
name: flutter_toll_map_app
version: 1.0.0+1
description: A cross-platform app to manage and view tolling sites

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  cloud_firestore: ^4.0.3
  firebase_core: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/site_data.json
```

